### ISSUE TITLE
Signaling server dying on browser close / disconnect?

### ISSUE THREAD

**Issue by ReactivityJS** [draeder/easypeers-signal#2]
Closed my browser and signaling server instance is dying:
```
rancher@rancher:~$ docker logs -f $(docker ps -qf name=easypeers)

> easypeers-signal@0.0.1 start
> node server.js

Sun Nov 26 2023 13:13:19 GMT+0000 (Coordinated Universal Time) Server is listening on port 8080
/easypeers/server.js:67
        clients[id].lastHeartbeat = Date.now();
                                  ^

TypeError: Cannot set properties of undefined (setting 'lastHeartbeat')
    at WebSocket.<anonymous> (/easypeers/server.js:67:35)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/easypeers/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/easypeers/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/easypeers/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/easypeers/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/easypeers/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
npm notice 
npm notice New major version of npm available! 8.11.0 -> 10.2.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice 
```

**Comment by bmatusiak** [comment]
https://github.com/draeder/easypeers-signal/blob/4ecaa1826ffc4c9b8d543adfa3fae4492462b1cf/server.js#L67

**Comment by draeder** [comment]
It looks like there should be a check for whether or not `clients[id]` exists before setting the lastHeartBeat property.

Something like:
`clients[id] ? clients[id].lastHeartbeat = Date.now() : delete clients[id]`

**Comment by draeder** [comment]
^^ Fixed. Local testing seemed to be okay.
